// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OrderMode string

const (
	OrderModeDelivery OrderMode = "delivery"
	OrderModePickup   OrderMode = "pickup"
	OrderModeDineIn   OrderMode = "dine_in"
)

func (e *OrderMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderMode(s)
	case string:
		*e = OrderMode(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderMode: %T", src)
	}
	return nil
}

type NullOrderMode struct {
	OrderMode OrderMode
	Valid     bool // Valid is true if OrderMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderMode) Scan(value interface{}) error {
	if value == nil {
		ns.OrderMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderMode), nil
}

func (e OrderMode) Valid() bool {
	switch e {
	case OrderModeDelivery,
		OrderModePickup,
		OrderModeDineIn:
		return true
	}
	return false
}

type OrderStatus string

const (
	OrderStatusOpen           OrderStatus = "open"
	OrderStatusNew            OrderStatus = "new"
	OrderStatusAccepted       OrderStatus = "accepted"
	OrderStatusPreparing      OrderStatus = "preparing"
	OrderStatusReady          OrderStatus = "ready"
	OrderStatusOutForDelivery OrderStatus = "out_for_delivery"
	OrderStatusCompleted      OrderStatus = "completed"
	OrderStatusCancelled      OrderStatus = "cancelled"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus
	Valid       bool // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

func (e OrderStatus) Valid() bool {
	switch e {
	case OrderStatusOpen,
		OrderStatusNew,
		OrderStatusAccepted,
		OrderStatusPreparing,
		OrderStatusReady,
		OrderStatusOutForDelivery,
		OrderStatusCompleted,
		OrderStatusCancelled:
		return true
	}
	return false
}

type PayMethod string

const (
	PayMethodCash  PayMethod = "cash"
	PayMethodCard  PayMethod = "card"
	PayMethodBkash PayMethod = "bkash"
	PayMethodNagad PayMethod = "nagad"
)

func (e *PayMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PayMethod(s)
	case string:
		*e = PayMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PayMethod: %T", src)
	}
	return nil
}

type NullPayMethod struct {
	PayMethod PayMethod
	Valid     bool // Valid is true if PayMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPayMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PayMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PayMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPayMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PayMethod), nil
}

func (e PayMethod) Valid() bool {
	switch e {
	case PayMethodCash,
		PayMethodCard,
		PayMethodBkash,
		PayMethodNagad:
		return true
	}
	return false
}

type Admin struct {
	ID           int64
	Email        *string
	Name         string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	Role         string
}

type Category struct {
	ID       int64
	Slug     string
	Name     string
	Position int32
}

type DiningTable struct {
	ID       int64
	Name     string
	Seats    int16
	Area     string
	Position int32
}

type KitchenTicket struct {
	ID        pgtype.UUID
	OrderID   pgtype.UUID
	Lines     []byte
	CreatedAt pgtype.Timestamptz
	DoneAt    pgtype.Timestamptz
}

type MenuItem struct {
	ID          int64
	CategoryID  int64
	Name        string
	Description string
	Price       int64
	Tags        []string
	Image       *string
	Available   bool
	Position    int32
}

type OpeningHour struct {
	Weekday int16
	Opens   pgtype.Time
	Closes  pgtype.Time
}

type Order struct {
	ID           pgtype.UUID
	Number       int64
	Mode         OrderMode
	Status       OrderStatus
	Payment      string
	CustomerName string
	Phone        *string
	Address      *string
	Note         *string
	Subtotal     int64
	DeliveryFee  int64
	Total        int64
	CreatedAt    pgtype.Timestamptz
	Source       string
	TableID      *int64
	Discount     int64
	PaidAt       pgtype.Timestamptz
	CreatedBy    *int64
	VoidedBy     *int64
	Vat          int64
	VatRate      int32
	VatInclusive bool
}

type OrderItem struct {
	OrderID    pgtype.UUID
	MenuItemID int64
	Name       string
	UnitPrice  int64
	Qty        int32
	SentQty    int32
	Note       *string
}

type Payment struct {
	ID        pgtype.UUID
	OrderID   pgtype.UUID
	Method    PayMethod
	Amount    int64
	Tip       int64
	Reference *string
	CreatedAt pgtype.Timestamptz
	TakenBy   *int64
}

type Reservation struct {
	ID           pgtype.UUID
	CustomerName string
	Phone        string
	Guests       int16
	StartsAt     pgtype.Timestamptz
	Note         *string
	Status       string
	CreatedAt    pgtype.Timestamptz
}

type Restaurant struct {
	ID               int32
	Name             string
	Area             string
	Address          string
	Phone            string
	Whatsapp         string
	Email            string
	DeliveryFee      int64
	FreeDeliveryOver int64
	DeliveryAreas    string
	DeliveryEta      string
	PickupEta        string
	VatRate          int32
	VatInclusive     bool
	Bin              string
	Theme            string
}

type Session struct {
	TokenHash []byte
	AdminID   int64
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type SiteContent struct {
	ID        int32
	Data      []byte
	UpdatedAt pgtype.Timestamptz
}
