// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMenuItems = `-- name: GetMenuItems :many
select id, category_id, name, description, price, tags, image, available, position from menu_items where id = any($1::bigint[])
`

func (q *Queries) GetMenuItems(ctx context.Context, ids []int64) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, getMenuItems, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuItem
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Tags,
			&i.Image,
			&i.Available,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpeningHours = `-- name: GetOpeningHours :one
select weekday, opens, closes from opening_hours where weekday = $1
`

func (q *Queries) GetOpeningHours(ctx context.Context, weekday int16) (OpeningHour, error) {
	row := q.db.QueryRow(ctx, getOpeningHours, weekday)
	var i OpeningHour
	err := row.Scan(&i.Weekday, &i.Opens, &i.Closes)
	return i, err
}

const getOrder = `-- name: GetOrder :one
select id, number, mode, status, payment, customer_name, phone, address, note, subtotal, delivery_fee, total, created_at from orders where id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Mode,
		&i.Status,
		&i.Payment,
		&i.CustomerName,
		&i.Phone,
		&i.Address,
		&i.Note,
		&i.Subtotal,
		&i.DeliveryFee,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const getReservation = `-- name: GetReservation :one
select id, customer_name, phone, guests, starts_at, note, status, created_at from reservations where id = $1
`

func (q *Queries) GetReservation(ctx context.Context, id pgtype.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservation, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.CustomerName,
		&i.Phone,
		&i.Guests,
		&i.StartsAt,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getRestaurant = `-- name: GetRestaurant :one
select id, name, area, address, phone, whatsapp, email, delivery_fee, free_delivery_over, delivery_areas, delivery_eta, pickup_eta from restaurant where id = 1
`

func (q *Queries) GetRestaurant(ctx context.Context) (Restaurant, error) {
	row := q.db.QueryRow(ctx, getRestaurant)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Area,
		&i.Address,
		&i.Phone,
		&i.Whatsapp,
		&i.Email,
		&i.DeliveryFee,
		&i.FreeDeliveryOver,
		&i.DeliveryAreas,
		&i.DeliveryEta,
		&i.PickupEta,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :execrows
insert into orders (id, mode, customer_name, phone, address, note, subtotal, delivery_fee, total)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
on conflict (id) do nothing
`

type InsertOrderParams struct {
	ID           pgtype.UUID
	Mode         OrderMode
	CustomerName string
	Phone        string
	Address      *string
	Note         *string
	Subtotal     int64
	DeliveryFee  int64
	Total        int64
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertOrder,
		arg.ID,
		arg.Mode,
		arg.CustomerName,
		arg.Phone,
		arg.Address,
		arg.Note,
		arg.Subtotal,
		arg.DeliveryFee,
		arg.Total,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertOrderItem = `-- name: InsertOrderItem :exec
insert into order_items (order_id, menu_item_id, name, unit_price, qty) values ($1, $2, $3, $4, $5)
`

type InsertOrderItemParams struct {
	OrderID    pgtype.UUID
	MenuItemID int64
	Name       string
	UnitPrice  int64
	Qty        int32
}

func (q *Queries) InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) error {
	_, err := q.db.Exec(ctx, insertOrderItem,
		arg.OrderID,
		arg.MenuItemID,
		arg.Name,
		arg.UnitPrice,
		arg.Qty,
	)
	return err
}

const insertReservation = `-- name: InsertReservation :execrows
insert into reservations (id, customer_name, phone, guests, starts_at, note)
values ($1, $2, $3, $4, $5, $6)
on conflict (id) do nothing
`

type InsertReservationParams struct {
	ID           pgtype.UUID
	CustomerName string
	Phone        string
	Guests       int16
	StartsAt     pgtype.Timestamptz
	Note         *string
}

func (q *Queries) InsertReservation(ctx context.Context, arg InsertReservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertReservation,
		arg.ID,
		arg.CustomerName,
		arg.Phone,
		arg.Guests,
		arg.StartsAt,
		arg.Note,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listMenu = `-- name: ListMenu :many
select c.slug as category_slug, c.name as category_name, i.id, i.category_id, i.name, i.description, i.price, i.tags, i.image, i.available, i.position
from menu_items i
join categories c on c.id = i.category_id
order by c.position, i.position
`

type ListMenuRow struct {
	CategorySlug string
	CategoryName string
	ID           int64
	CategoryID   int64
	Name         string
	Description  string
	Price        int64
	Tags         []string
	Image        *string
	Available    bool
	Position     int32
}

func (q *Queries) ListMenu(ctx context.Context) ([]ListMenuRow, error) {
	rows, err := q.db.Query(ctx, listMenu)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMenuRow
	for rows.Next() {
		var i ListMenuRow
		if err := rows.Scan(
			&i.CategorySlug,
			&i.CategoryName,
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Tags,
			&i.Image,
			&i.Available,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpeningHours = `-- name: ListOpeningHours :many
select weekday, opens, closes from opening_hours order by weekday
`

func (q *Queries) ListOpeningHours(ctx context.Context) ([]OpeningHour, error) {
	rows, err := q.db.Query(ctx, listOpeningHours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpeningHour
	for rows.Next() {
		var i OpeningHour
		if err := rows.Scan(&i.Weekday, &i.Opens, &i.Closes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItems = `-- name: ListOrderItems :many
select order_id, menu_item_id, name, unit_price, qty from order_items where order_id = $1 order by name
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.OrderID,
			&i.MenuItemID,
			&i.Name,
			&i.UnitPrice,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
