// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeOrder = `-- name: CloseOrder :exec
update orders set status = $1, paid_at = case when $1 = 'completed'::order_status then now() else paid_at end
where id = $2
`

type CloseOrderParams struct {
	Status OrderStatus
	ID     pgtype.UUID
}

func (q *Queries) CloseOrder(ctx context.Context, arg CloseOrderParams) error {
	_, err := q.db.Exec(ctx, closeOrder, arg.Status, arg.ID)
	return err
}

const countCategoryItems = `-- name: CountCategoryItems :one
select count(*) from menu_items where category_id = $1
`

func (q *Queries) CountCategoryItems(ctx context.Context, categoryID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoryItems, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countItemOrders = `-- name: CountItemOrders :one
select count(*) from order_items where menu_item_id = $1
`

func (q *Queries) CountItemOrders(ctx context.Context, menuItemID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countItemOrders, menuItemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countKitchenTickets = `-- name: CountKitchenTickets :one
select count(*) from kitchen_tickets where order_id = $1
`

func (q *Queries) CountKitchenTickets(ctx context.Context, orderID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countKitchenTickets, orderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one
insert into admins (email, name, password_hash) values ($1, $2, $3) returning id
`

type CreateAdminParams struct {
	Email        string
	Name         string
	PasswordHash string
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAdmin, arg.Email, arg.Name, arg.PasswordHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createCategory = `-- name: CreateCategory :one
insert into categories (slug, name, position)
values ($1, $2, (select coalesce(max(position), 0) + 1 from categories))
returning id, slug, name, position
`

type CreateCategoryParams struct {
	Slug string
	Name string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Slug, arg.Name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Position,
	)
	return i, err
}

const createMenuItem = `-- name: CreateMenuItem :one
insert into menu_items (category_id, name, description, price, tags, image, available, position)
values ($1, $2, $3, $4, $5, $6, $7, (select coalesce(max(position), 0) + 1 from menu_items where category_id = $1))
returning id, category_id, name, description, price, tags, image, available, position
`

type CreateMenuItemParams struct {
	CategoryID  int64
	Name        string
	Description string
	Price       int64
	Tags        []string
	Image       *string
	Available   bool
}

func (q *Queries) CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, createMenuItem,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Tags,
		arg.Image,
		arg.Available,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Tags,
		&i.Image,
		&i.Available,
		&i.Position,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
insert into sessions (token_hash, admin_id, expires_at) values ($1, $2, $3)
`

type CreateSessionParams struct {
	TokenHash []byte
	AdminID   int64
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.AdminID, arg.ExpiresAt)
	return err
}

const createTable = `-- name: CreateTable :one
insert into dining_tables (name, seats, area, position)
values ($1, $2, $3, (select coalesce(max(position), 0) + 1 from dining_tables))
returning id, name, seats, area, position
`

type CreateTableParams struct {
	Name  string
	Seats int16
	Area  string
}

func (q *Queries) CreateTable(ctx context.Context, arg CreateTableParams) (DiningTable, error) {
	row := q.db.QueryRow(ctx, createTable, arg.Name, arg.Seats, arg.Area)
	var i DiningTable
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Seats,
		&i.Area,
		&i.Position,
	)
	return i, err
}

const customerOrderStats = `-- name: CustomerOrderStats :one
select count(*)::int as orders, coalesce(sum(total), 0)::bigint as spent, max(created_at)::timestamptz as last_at
from orders where phone = $1 and status not in ('cancelled', 'open')
`

type CustomerOrderStatsRow struct {
	Orders int32
	Spent  int64
	LastAt pgtype.Timestamptz
}

func (q *Queries) CustomerOrderStats(ctx context.Context, phone *string) (CustomerOrderStatsRow, error) {
	row := q.db.QueryRow(ctx, customerOrderStats, phone)
	var i CustomerOrderStatsRow
	err := row.Scan(&i.Orders, &i.Spent, &i.LastAt)
	return i, err
}

const dailySales = `-- name: DailySales :many

select (created_at at time zone 'Asia/Dhaka')::date as day,
	count(*) filter (where status not in ('cancelled', 'open')) as orders,
	coalesce(sum(total) filter (where status not in ('cancelled', 'open')), 0)::bigint as revenue
from orders
where created_at >= $1 and created_at < $2
group by 1
order by 1
`

type DailySalesParams struct {
	Since pgtype.Timestamptz
	Until pgtype.Timestamptz
}

type DailySalesRow struct {
	Day     pgtype.Date
	Orders  int64
	Revenue int64
}

// ---- Overview (days are Bangladesh calendar days)
func (q *Queries) DailySales(ctx context.Context, arg DailySalesParams) ([]DailySalesRow, error) {
	rows, err := q.db.Query(ctx, dailySales, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailySalesRow
	for rows.Next() {
		var i DailySalesRow
		if err := rows.Scan(&i.Day, &i.Orders, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCategory = `-- name: DeleteCategory :execrows
delete from categories where id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
delete from sessions where expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteMenuItem = `-- name: DeleteMenuItem :execrows
delete from menu_items where id = $1
`

func (q *Queries) DeleteMenuItem(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMenuItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOpeningHours = `-- name: DeleteOpeningHours :exec
delete from opening_hours
`

func (q *Queries) DeleteOpeningHours(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOpeningHours)
	return err
}

const deleteOrderItems = `-- name: DeleteOrderItems :exec
delete from order_items where order_id = $1
`

func (q *Queries) DeleteOrderItems(ctx context.Context, orderID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrderItems, orderID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
delete from sessions where token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteTable = `-- name: DeleteTable :execrows
delete from dining_tables t where t.id = $1
	and not exists (select 1 from orders o where o.table_id = t.id)
`

func (q *Queries) DeleteTable(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTable, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
select id, email, name, password_hash, created_at from admins where email = $1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getMenuItems = `-- name: GetMenuItems :many
select id, category_id, name, description, price, tags, image, available, position from menu_items where id = any($1::bigint[])
`

func (q *Queries) GetMenuItems(ctx context.Context, ids []int64) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, getMenuItems, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuItem
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Tags,
			&i.Image,
			&i.Available,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpeningHours = `-- name: GetOpeningHours :one
select weekday, opens, closes from opening_hours where weekday = $1
`

func (q *Queries) GetOpeningHours(ctx context.Context, weekday int16) (OpeningHour, error) {
	row := q.db.QueryRow(ctx, getOpeningHours, weekday)
	var i OpeningHour
	err := row.Scan(&i.Weekday, &i.Opens, &i.Closes)
	return i, err
}

const getOrder = `-- name: GetOrder :one
select id, number, mode, status, payment, customer_name, phone, address, note, subtotal, delivery_fee, total, created_at, source, table_id, discount, paid_at from orders where id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Mode,
		&i.Status,
		&i.Payment,
		&i.CustomerName,
		&i.Phone,
		&i.Address,
		&i.Note,
		&i.Subtotal,
		&i.DeliveryFee,
		&i.Total,
		&i.CreatedAt,
		&i.Source,
		&i.TableID,
		&i.Discount,
		&i.PaidAt,
	)
	return i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
select id, number, mode, status, payment, customer_name, phone, address, note, subtotal, delivery_fee, total, created_at, source, table_id, discount, paid_at from orders where id = $1 for update
`

func (q *Queries) GetOrderForUpdate(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderForUpdate, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Mode,
		&i.Status,
		&i.Payment,
		&i.CustomerName,
		&i.Phone,
		&i.Address,
		&i.Note,
		&i.Subtotal,
		&i.DeliveryFee,
		&i.Total,
		&i.CreatedAt,
		&i.Source,
		&i.TableID,
		&i.Discount,
		&i.PaidAt,
	)
	return i, err
}

const getReservation = `-- name: GetReservation :one
select id, customer_name, phone, guests, starts_at, note, status, created_at from reservations where id = $1
`

func (q *Queries) GetReservation(ctx context.Context, id pgtype.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservation, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.CustomerName,
		&i.Phone,
		&i.Guests,
		&i.StartsAt,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getRestaurant = `-- name: GetRestaurant :one
select id, name, area, address, phone, whatsapp, email, delivery_fee, free_delivery_over, delivery_areas, delivery_eta, pickup_eta from restaurant where id = 1
`

func (q *Queries) GetRestaurant(ctx context.Context) (Restaurant, error) {
	row := q.db.QueryRow(ctx, getRestaurant)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Area,
		&i.Address,
		&i.Phone,
		&i.Whatsapp,
		&i.Email,
		&i.DeliveryFee,
		&i.FreeDeliveryOver,
		&i.DeliveryAreas,
		&i.DeliveryEta,
		&i.PickupEta,
	)
	return i, err
}

const getSessionAdmin = `-- name: GetSessionAdmin :one
select a.id, a.email, a.name
from sessions s join admins a on a.id = s.admin_id
where s.token_hash = $1 and s.expires_at > now()
`

type GetSessionAdminRow struct {
	ID    int64
	Email string
	Name  string
}

func (q *Queries) GetSessionAdmin(ctx context.Context, tokenHash []byte) (GetSessionAdminRow, error) {
	row := q.db.QueryRow(ctx, getSessionAdmin, tokenHash)
	var i GetSessionAdminRow
	err := row.Scan(&i.ID, &i.Email, &i.Name)
	return i, err
}

const getSiteContent = `-- name: GetSiteContent :one

select data from site_content where id = 1
`

// ---- CMS
func (q *Queries) GetSiteContent(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSiteContent)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const insertKitchenTicket = `-- name: InsertKitchenTicket :execrows
insert into kitchen_tickets (id, order_id, lines) values ($1, $2, $3) on conflict (id) do nothing
`

type InsertKitchenTicketParams struct {
	ID      pgtype.UUID
	OrderID pgtype.UUID
	Lines   []byte
}

func (q *Queries) InsertKitchenTicket(ctx context.Context, arg InsertKitchenTicketParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertKitchenTicket, arg.ID, arg.OrderID, arg.Lines)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertOpeningHours = `-- name: InsertOpeningHours :exec
insert into opening_hours (weekday, opens, closes) values ($1, $2, $3)
`

type InsertOpeningHoursParams struct {
	Weekday int16
	Opens   pgtype.Time
	Closes  pgtype.Time
}

func (q *Queries) InsertOpeningHours(ctx context.Context, arg InsertOpeningHoursParams) error {
	_, err := q.db.Exec(ctx, insertOpeningHours, arg.Weekday, arg.Opens, arg.Closes)
	return err
}

const insertOrder = `-- name: InsertOrder :execrows
insert into orders (id, mode, customer_name, phone, address, note, subtotal, delivery_fee, total)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
on conflict (id) do nothing
`

type InsertOrderParams struct {
	ID           pgtype.UUID
	Mode         OrderMode
	CustomerName string
	Phone        *string
	Address      *string
	Note         *string
	Subtotal     int64
	DeliveryFee  int64
	Total        int64
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertOrder,
		arg.ID,
		arg.Mode,
		arg.CustomerName,
		arg.Phone,
		arg.Address,
		arg.Note,
		arg.Subtotal,
		arg.DeliveryFee,
		arg.Total,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertOrderItem = `-- name: InsertOrderItem :exec
insert into order_items (order_id, menu_item_id, name, unit_price, qty) values ($1, $2, $3, $4, $5)
`

type InsertOrderItemParams struct {
	OrderID    pgtype.UUID
	MenuItemID int64
	Name       string
	UnitPrice  int64
	Qty        int32
}

func (q *Queries) InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) error {
	_, err := q.db.Exec(ctx, insertOrderItem,
		arg.OrderID,
		arg.MenuItemID,
		arg.Name,
		arg.UnitPrice,
		arg.Qty,
	)
	return err
}

const insertPayment = `-- name: InsertPayment :execrows
insert into payments (id, order_id, method, amount, tip, reference) values ($1, $2, $3, $4, $5, $6)
on conflict (id) do nothing
`

type InsertPaymentParams struct {
	ID        pgtype.UUID
	OrderID   pgtype.UUID
	Method    PayMethod
	Amount    int64
	Tip       int64
	Reference *string
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPayment,
		arg.ID,
		arg.OrderID,
		arg.Method,
		arg.Amount,
		arg.Tip,
		arg.Reference,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPosItem = `-- name: InsertPosItem :exec
insert into order_items (order_id, menu_item_id, name, unit_price, qty, sent_qty) values ($1, $2, $3, $4, $5, $6)
`

type InsertPosItemParams struct {
	OrderID    pgtype.UUID
	MenuItemID int64
	Name       string
	UnitPrice  int64
	Qty        int32
	SentQty    int32
}

func (q *Queries) InsertPosItem(ctx context.Context, arg InsertPosItemParams) error {
	_, err := q.db.Exec(ctx, insertPosItem,
		arg.OrderID,
		arg.MenuItemID,
		arg.Name,
		arg.UnitPrice,
		arg.Qty,
		arg.SentQty,
	)
	return err
}

const insertPosOrder = `-- name: InsertPosOrder :exec
insert into orders (id, mode, status, source, table_id, customer_name, phone, note, subtotal, delivery_fee, discount, total)
values ($1, $2, 'open', 'pos', $3, $4, $5, $6, $7, 0, $8, $9)
`

type InsertPosOrderParams struct {
	ID           pgtype.UUID
	Mode         OrderMode
	TableID      *int64
	CustomerName string
	Phone        *string
	Note         *string
	Subtotal     int64
	Discount     int64
	Total        int64
}

func (q *Queries) InsertPosOrder(ctx context.Context, arg InsertPosOrderParams) error {
	_, err := q.db.Exec(ctx, insertPosOrder,
		arg.ID,
		arg.Mode,
		arg.TableID,
		arg.CustomerName,
		arg.Phone,
		arg.Note,
		arg.Subtotal,
		arg.Discount,
		arg.Total,
	)
	return err
}

const insertReservation = `-- name: InsertReservation :execrows
insert into reservations (id, customer_name, phone, guests, starts_at, note)
values ($1, $2, $3, $4, $5, $6)
on conflict (id) do nothing
`

type InsertReservationParams struct {
	ID           pgtype.UUID
	CustomerName string
	Phone        string
	Guests       int16
	StartsAt     pgtype.Timestamptz
	Note         *string
}

func (q *Queries) InsertReservation(ctx context.Context, arg InsertReservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertReservation,
		arg.ID,
		arg.CustomerName,
		arg.Phone,
		arg.Guests,
		arg.StartsAt,
		arg.Note,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const kitchenBoard = `-- name: KitchenBoard :many
select k.id, k.order_id, k.lines, k.created_at, k.done_at, o.number, o.mode, o.source, t.name as table_name, o.customer_name
from kitchen_tickets k
join orders o on o.id = k.order_id
left join dining_tables t on t.id = o.table_id
where k.done_at is null or k.done_at > now() - interval '30 minutes'
order by k.done_at nulls first, k.created_at
`

type KitchenBoardRow struct {
	ID           pgtype.UUID
	OrderID      pgtype.UUID
	Lines        []byte
	CreatedAt    pgtype.Timestamptz
	DoneAt       pgtype.Timestamptz
	Number       int64
	Mode         OrderMode
	Source       string
	TableName    *string
	CustomerName string
}

func (q *Queries) KitchenBoard(ctx context.Context) ([]KitchenBoardRow, error) {
	rows, err := q.db.Query(ctx, kitchenBoard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KitchenBoardRow
	for rows.Next() {
		var i KitchenBoardRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Lines,
			&i.CreatedAt,
			&i.DoneAt,
			&i.Number,
			&i.Mode,
			&i.Source,
			&i.TableName,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const kitchenTicketExists = `-- name: KitchenTicketExists :one
select exists (select 1 from kitchen_tickets where id = $1)
`

func (q *Queries) KitchenTicketExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, kitchenTicketExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listCategories = `-- name: ListCategories :many
select id, slug, name, position from categories order by position
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenu = `-- name: ListMenu :many
select c.slug as category_slug, c.name as category_name, i.id, i.category_id, i.name, i.description, i.price, i.tags, i.image, i.available, i.position
from menu_items i
join categories c on c.id = i.category_id
order by c.position, i.position
`

type ListMenuRow struct {
	CategorySlug string
	CategoryName string
	ID           int64
	CategoryID   int64
	Name         string
	Description  string
	Price        int64
	Tags         []string
	Image        *string
	Available    bool
	Position     int32
}

func (q *Queries) ListMenu(ctx context.Context) ([]ListMenuRow, error) {
	rows, err := q.db.Query(ctx, listMenu)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMenuRow
	for rows.Next() {
		var i ListMenuRow
		if err := rows.Scan(
			&i.CategorySlug,
			&i.CategoryName,
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Tags,
			&i.Image,
			&i.Available,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpeningHours = `-- name: ListOpeningHours :many
select weekday, opens, closes from opening_hours order by weekday
`

func (q *Queries) ListOpeningHours(ctx context.Context) ([]OpeningHour, error) {
	rows, err := q.db.Query(ctx, listOpeningHours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpeningHour
	for rows.Next() {
		var i OpeningHour
		if err := rows.Scan(&i.Weekday, &i.Opens, &i.Closes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItems = `-- name: ListOrderItems :many
select order_id, menu_item_id, name, unit_price, qty, sent_qty from order_items where order_id = $1 order by name
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.OrderID,
			&i.MenuItemID,
			&i.Name,
			&i.UnitPrice,
			&i.Qty,
			&i.SentQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsFor = `-- name: ListOrderItemsFor :many
select order_id, menu_item_id, name, unit_price, qty, sent_qty from order_items where order_id = any($1::uuid[]) order by name
`

func (q *Queries) ListOrderItemsFor(ctx context.Context, ids []pgtype.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsFor, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.OrderID,
			&i.MenuItemID,
			&i.Name,
			&i.UnitPrice,
			&i.Qty,
			&i.SentQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
select id, number, mode, status, payment, customer_name, phone, address, note, subtotal, delivery_fee, total, created_at, source, table_id, discount, paid_at from orders
where ($1::order_status is null or status = $1)
	and (not $2::bool or status not in ('completed', 'cancelled', 'open'))
order by created_at desc
limit 200
`

type ListOrdersParams struct {
	Status     *OrderStatus
	ActiveOnly bool
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders, arg.Status, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Mode,
			&i.Status,
			&i.Payment,
			&i.CustomerName,
			&i.Phone,
			&i.Address,
			&i.Note,
			&i.Subtotal,
			&i.DeliveryFee,
			&i.Total,
			&i.CreatedAt,
			&i.Source,
			&i.TableID,
			&i.Discount,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayments = `-- name: ListPayments :many
select id, order_id, method, amount, tip, reference, created_at from payments where order_id = $1 order by created_at
`

func (q *Queries) ListPayments(ctx context.Context, orderID pgtype.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPayments, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Method,
			&i.Amount,
			&i.Tip,
			&i.Reference,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservations = `-- name: ListReservations :many
select id, customer_name, phone, guests, starts_at, note, status, created_at from reservations
where starts_at >= now() - interval '1 day' or status = 'requested'
order by starts_at
limit 200
`

func (q *Queries) ListReservations(ctx context.Context) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.CustomerName,
			&i.Phone,
			&i.Guests,
			&i.StartsAt,
			&i.Note,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByPhone = `-- name: ListReservationsByPhone :many
select id, customer_name, phone, guests, starts_at, note, status, created_at from reservations where phone = $1 and id <> $2 order by starts_at desc limit 10
`

type ListReservationsByPhoneParams struct {
	Phone string
	ID    pgtype.UUID
}

func (q *Queries) ListReservationsByPhone(ctx context.Context, arg ListReservationsByPhoneParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByPhone, arg.Phone, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.CustomerName,
			&i.Phone,
			&i.Guests,
			&i.StartsAt,
			&i.Note,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTables = `-- name: ListTables :many

select id, name, seats, area, position from dining_tables order by position, name
`

// ---- POS
func (q *Queries) ListTables(ctx context.Context) ([]DiningTable, error) {
	rows, err := q.db.Query(ctx, listTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiningTable
	for rows.Next() {
		var i DiningTable
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Seats,
			&i.Area,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllSent = `-- name: MarkAllSent :exec
update order_items set sent_qty = qty where order_id = $1
`

func (q *Queries) MarkAllSent(ctx context.Context, orderID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllSent, orderID)
	return err
}

const openOrderCounts = `-- name: OpenOrderCounts :many
select status, count(*) as n from orders
where status not in ('completed', 'cancelled', 'open')
group by status
`

type OpenOrderCountsRow struct {
	Status OrderStatus
	N      int64
}

func (q *Queries) OpenOrderCounts(ctx context.Context) ([]OpenOrderCountsRow, error) {
	rows, err := q.db.Query(ctx, openOrderCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpenOrderCountsRow
	for rows.Next() {
		var i OpenOrderCountsRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openTickets = `-- name: OpenTickets :many
select o.id, o.number, o.mode, o.status, o.payment, o.customer_name, o.phone, o.address, o.note, o.subtotal, o.delivery_fee, o.total, o.created_at, o.source, o.table_id, o.discount, o.paid_at, t.name as table_name,
	(select coalesce(sum(qty - sent_qty), 0) from order_items where order_id = o.id)::bigint as unsent,
	(select coalesce(sum(amount), 0) from payments where order_id = o.id)::bigint as paid
from orders o
left join dining_tables t on t.id = o.table_id
where o.status = 'open'
order by o.created_at
`

type OpenTicketsRow struct {
	ID           pgtype.UUID
	Number       int64
	Mode         OrderMode
	Status       OrderStatus
	Payment      string
	CustomerName string
	Phone        *string
	Address      *string
	Note         *string
	Subtotal     int64
	DeliveryFee  int64
	Total        int64
	CreatedAt    pgtype.Timestamptz
	Source       string
	TableID      *int64
	Discount     int64
	PaidAt       pgtype.Timestamptz
	TableName    *string
	Unsent       int64
	Paid         int64
}

func (q *Queries) OpenTickets(ctx context.Context) ([]OpenTicketsRow, error) {
	rows, err := q.db.Query(ctx, openTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpenTicketsRow
	for rows.Next() {
		var i OpenTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Mode,
			&i.Status,
			&i.Payment,
			&i.CustomerName,
			&i.Phone,
			&i.Address,
			&i.Note,
			&i.Subtotal,
			&i.DeliveryFee,
			&i.Total,
			&i.CreatedAt,
			&i.Source,
			&i.TableID,
			&i.Discount,
			&i.PaidAt,
			&i.TableName,
			&i.Unsent,
			&i.Paid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paidTotal = `-- name: PaidTotal :one
select coalesce(sum(amount), 0)::bigint from payments where order_id = $1
`

func (q *Queries) PaidTotal(ctx context.Context, orderID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, paidTotal, orderID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const periodTotals = `-- name: PeriodTotals :one
select count(*) filter (where status not in ('cancelled', 'open')) as orders,
	coalesce(sum(total) filter (where status not in ('cancelled', 'open')), 0)::bigint as revenue,
	count(*) filter (where status = 'cancelled') as cancelled,
	count(*) filter (where status not in ('cancelled', 'open') and mode = 'delivery') as delivery,
	count(*) filter (where status not in ('cancelled', 'open') and mode = 'pickup') as pickup,
	count(*) filter (where status not in ('cancelled', 'open') and mode = 'dine_in') as dine_in
from orders
where created_at >= $1 and created_at < $2
`

type PeriodTotalsParams struct {
	Since pgtype.Timestamptz
	Until pgtype.Timestamptz
}

type PeriodTotalsRow struct {
	Orders    int64
	Revenue   int64
	Cancelled int64
	Delivery  int64
	Pickup    int64
	DineIn    int64
}

func (q *Queries) PeriodTotals(ctx context.Context, arg PeriodTotalsParams) (PeriodTotalsRow, error) {
	row := q.db.QueryRow(ctx, periodTotals, arg.Since, arg.Until)
	var i PeriodTotalsRow
	err := row.Scan(
		&i.Orders,
		&i.Revenue,
		&i.Cancelled,
		&i.Delivery,
		&i.Pickup,
		&i.DineIn,
	)
	return i, err
}

const setTicketDone = `-- name: SetTicketDone :execrows
update kitchen_tickets set done_at = case when $1::bool then now() else null end where id = $2
`

type SetTicketDoneParams struct {
	Done bool
	ID   pgtype.UUID
}

func (q *Queries) SetTicketDone(ctx context.Context, arg SetTicketDoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTicketDone, arg.Done, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const topItems = `-- name: TopItems :many
select oi.name, sum(oi.qty)::bigint as qty, sum(oi.qty * oi.unit_price)::bigint as revenue
from order_items oi
join orders o on o.id = oi.order_id
where o.created_at >= $1 and o.created_at < $2 and o.status not in ('cancelled', 'open')
group by oi.name
order by qty desc, revenue desc
limit 5
`

type TopItemsParams struct {
	Since pgtype.Timestamptz
	Until pgtype.Timestamptz
}

type TopItemsRow struct {
	Name    string
	Qty     int64
	Revenue int64
}

func (q *Queries) TopItems(ctx context.Context, arg TopItemsParams) ([]TopItemsRow, error) {
	rows, err := q.db.Query(ctx, topItems, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopItemsRow
	for rows.Next() {
		var i TopItemsRow
		if err := rows.Scan(&i.Name, &i.Qty, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upcomingBookings = `-- name: UpcomingBookings :many
select id, customer_name, phone, guests, starts_at, note, status, created_at from reservations
where starts_at >= now() and status in ('requested', 'confirmed')
order by starts_at
limit 5
`

func (q *Queries) UpcomingBookings(ctx context.Context) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, upcomingBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.CustomerName,
			&i.Phone,
			&i.Guests,
			&i.StartsAt,
			&i.Note,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :execrows
update categories set name = $2, slug = $3, position = $4 where id = $1
`

type UpdateCategoryParams struct {
	ID       int64
	Name     string
	Slug     string
	Position int32
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Position,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMenuItem = `-- name: UpdateMenuItem :execrows
update menu_items set category_id = $2, name = $3, description = $4, price = $5, tags = $6,
	image = $7, available = $8, position = $9
where id = $1
`

type UpdateMenuItemParams struct {
	ID          int64
	CategoryID  int64
	Name        string
	Description string
	Price       int64
	Tags        []string
	Image       *string
	Available   bool
	Position    int32
}

func (q *Queries) UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMenuItem,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Tags,
		arg.Image,
		arg.Available,
		arg.Position,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :execrows
update orders set status = $1 where id = $2 and source = 'online' and $1::order_status <> 'open'
`

type UpdateOrderStatusParams struct {
	Status OrderStatus
	ID     pgtype.UUID
}

// Online orders only; POS tickets change state through the POS endpoints.
func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrderStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePosOrder = `-- name: UpdatePosOrder :exec
update orders set mode = $2, table_id = $3, customer_name = $4, phone = $5, note = $6,
	subtotal = $7, discount = $8, total = $9
where id = $1
`

type UpdatePosOrderParams struct {
	ID           pgtype.UUID
	Mode         OrderMode
	TableID      *int64
	CustomerName string
	Phone        *string
	Note         *string
	Subtotal     int64
	Discount     int64
	Total        int64
}

func (q *Queries) UpdatePosOrder(ctx context.Context, arg UpdatePosOrderParams) error {
	_, err := q.db.Exec(ctx, updatePosOrder,
		arg.ID,
		arg.Mode,
		arg.TableID,
		arg.CustomerName,
		arg.Phone,
		arg.Note,
		arg.Subtotal,
		arg.Discount,
		arg.Total,
	)
	return err
}

const updateReservationStatus = `-- name: UpdateReservationStatus :execrows
update reservations set status = $2 where id = $1
`

type UpdateReservationStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateReservationStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRestaurant = `-- name: UpdateRestaurant :exec
update restaurant set name = $1, area = $2, address = $3, phone = $4, whatsapp = $5, email = $6,
	delivery_fee = $7, free_delivery_over = $8, delivery_areas = $9, delivery_eta = $10, pickup_eta = $11
where id = 1
`

type UpdateRestaurantParams struct {
	Name             string
	Area             string
	Address          string
	Phone            string
	Whatsapp         string
	Email            string
	DeliveryFee      int64
	FreeDeliveryOver int64
	DeliveryAreas    string
	DeliveryEta      string
	PickupEta        string
}

func (q *Queries) UpdateRestaurant(ctx context.Context, arg UpdateRestaurantParams) error {
	_, err := q.db.Exec(ctx, updateRestaurant,
		arg.Name,
		arg.Area,
		arg.Address,
		arg.Phone,
		arg.Whatsapp,
		arg.Email,
		arg.DeliveryFee,
		arg.FreeDeliveryOver,
		arg.DeliveryAreas,
		arg.DeliveryEta,
		arg.PickupEta,
	)
	return err
}

const updateSiteContent = `-- name: UpdateSiteContent :exec
update site_content set data = $1, updated_at = now() where id = 1
`

func (q *Queries) UpdateSiteContent(ctx context.Context, data []byte) error {
	_, err := q.db.Exec(ctx, updateSiteContent, data)
	return err
}

const updateTable = `-- name: UpdateTable :execrows
update dining_tables set name = $2, seats = $3, area = $4 where id = $1
`

type UpdateTableParams struct {
	ID    int64
	Name  string
	Seats int16
	Area  string
}

func (q *Queries) UpdateTable(ctx context.Context, arg UpdateTableParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTable,
		arg.ID,
		arg.Name,
		arg.Seats,
		arg.Area,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
