-- +goose Up
-- All money is integer poisha (৳1 = 100).

create table restaurant (
	id int primary key default 1 check (id = 1),
	name text not null,
	area text not null,
	address text not null,
	phone text not null,
	whatsapp text not null,
	email text not null,
	delivery_fee bigint not null check (delivery_fee >= 0),
	free_delivery_over bigint not null check (free_delivery_over >= 0),
	delivery_areas text not null,
	delivery_eta text not null,
	pickup_eta text not null
);

-- weekday: 0 = Sunday … 6 = Saturday, matching JS Date.getDay().
create table opening_hours (
	weekday smallint primary key check (weekday between 0 and 6),
	opens time not null,
	closes time not null check (closes > opens)
);

create table categories (
	id bigint generated always as identity primary key,
	slug text not null unique,
	name text not null,
	position int not null
);

create table menu_items (
	id bigint generated always as identity primary key,
	category_id bigint not null references categories,
	name text not null unique,
	description text not null default '',
	price bigint not null check (price > 0),
	tags text[] not null default '{}' check (tags <@ array['veg', 'spicy', 'popular']),
	image text,
	available boolean not null default true,
	position int not null
);

create type order_mode as enum ('delivery', 'pickup');
create type order_status as enum ('new', 'accepted', 'preparing', 'ready', 'out_for_delivery', 'completed', 'cancelled');
create sequence order_number_seq start 1001;

-- id is generated by the client so a retried submit never creates a second order.
create table orders (
	id uuid primary key,
	number bigint not null unique default nextval('order_number_seq'),
	mode order_mode not null,
	status order_status not null default 'new',
	payment text not null default 'cash' check (payment in ('cash')),
	customer_name text not null,
	phone text not null,
	address text,
	note text,
	subtotal bigint not null,
	delivery_fee bigint not null,
	total bigint not null,
	created_at timestamptz not null default now(),
	check (mode = 'pickup' or address is not null)
);

create table order_items (
	order_id uuid not null references orders on delete cascade,
	menu_item_id bigint not null references menu_items,
	name text not null,
	unit_price bigint not null,
	qty int not null check (qty between 1 and 50),
	primary key (order_id, menu_item_id)
);

create table reservations (
	id uuid primary key,
	customer_name text not null,
	phone text not null,
	guests smallint not null check (guests between 1 and 12),
	starts_at timestamptz not null,
	note text,
	status text not null default 'requested' check (status in ('requested', 'confirmed', 'declined', 'cancelled')),
	created_at timestamptz not null default now()
);

-- +goose Down
drop table reservations, order_items, orders, menu_items, categories, opening_hours, restaurant;
drop sequence order_number_seq;
drop type order_status, order_mode;
